# Generated by Django 5.0.3 on 2024-03-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='posted_on',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
