# Generated by Django 5.2.7 on 2025-11-05 12:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('pkid', models.BigAutoField(db_column='pkid', editable=False, primary_key=True, serialize=False)),
                ('id', models.UUIDField(db_column='id', default=uuid.uuid4, editable=False, unique=True)),
                ('username', models.CharField(db_column='username', max_length=25, unique=True, verbose_name='Username')),
                ('first_name', models.CharField(db_column='first_name', max_length=25, verbose_name='First Name')),
                ('last_name', models.CharField(db_column='last_name', max_length=25, verbose_name='Last Name')),
                ('email', models.EmailField(db_column='email', max_length=254, unique=True, verbose_name='Email Address')),
                ('is_staff', models.BooleanField(db_column='is_staff', default=False)),
                ('is_active', models.BooleanField(db_column='is_active', default=False)),
                ('date_created', models.DateTimeField(auto_now_add=True, db_column='date_created')),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'db_table': 'users',
            },
        ),
    ]
