# Generated by Django 5.2.7 on 2026-08-19 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(db_column='image', default='/default_photo.png', null=True, upload_to='blog_photo/')),
                ('url', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skills',
                'db_table': 'portfolio_portfolio',
            },
        ),
    ]
