# Generated by Django 5.2.7 on 2026-08-19 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='image',
            field=models.ImageField(db_column='image', default='/default_photo.png', null=True, upload_to='portfolio_photo/'),
        ),
    ]
