# Generated by Django 5.2.7 on 2026-08-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(db_column='image', default='/default_photo.png', null=True, upload_to='skill_photo/')),
            ],
            options={
                'verbose_name': 'Skills',
                'verbose_name_plural': 'Skills',
                'db_table': 'portfolio_skills',
            },
        ),
    ]
