# Generated by Django 5.2.7 on 2026-08-19 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Slug Field')),
                ('author', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('image', models.ImageField(db_column='image', default='/default_photo.png', null=True, upload_to='blog_photo/')),
                ('posted_on', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Blog',
                'verbose_name_plural': 'Blogs',
                'db_table': 'portfolio_blogs',
                'ordering': ['-posted_on'],
            },
        ),
    ]
