# Generated by Django 5.2.7 on 2026-08-20 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_blog_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='credit',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
