# Generated by Django 5.2.7 on 2026-08-20 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_blog_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='credit',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
