# Generated by Django 5.2.7 on 2026-08-21 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_alter_blog_credit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='image',
            field=models.ImageField(blank=True, db_column='image', default='media/blog_images/default.png', null=True, upload_to='blog_images/'),
        ),
    ]
