# Generated by Django 5.2.7 on 2026-09-22 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0007_alter_blog_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blog',
            old_name='content',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='blog',
            old_name='subtitle',
            new_name='intro',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='author',
        ),
        migrations.RemoveField(
            model_name='blog',
            name='views',
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(default='engineering', max_length=100),
        ),
        migrations.AddField(
            model_name='blog',
            name='read',
            field=models.PositiveIntegerField(default=4),
        ),
    ]
