# Generated by Django 5.2.7 on 2026-09-22 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0008_rename_content_blog_body_rename_subtitle_blog_intro_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('gis', 'gis'), ('database', 'database')], db_column='category', max_length=100, null=True),
        ),
    ]
